version: '3.8'

services:
  todo_api:
    build:
      context: ./todo_api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=mysql2://root:@db:3306/todo_api_development
    depends_on:
      - db

  todo_frontend:
    build:
      context: ./todo_frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    volumes:
      - ./todo_frontend:/app

  db:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

