# Use the official Node.js image
FROM node:21

# Set the working directory in the Docker container
WORKDIR /app

# Copy package.json
COPY package.json /app/

# Install dependencies
RUN npm install

# Copy the rest of the app's source code
COPY . /app

# Expose the port that the React dev server runs on
EXPOSE 80

# Start the React development server
CMD ["npm", "run", "dev"]
